#!/usr/bin/env python3
"""Regenerate the flamegraph analysis write-up from measured results.

Reads ``flamegraph_results.json`` (written by ``run_flamegraph.sh``) plus the
current ``pstats_cumulative.txt`` / ``pstats_tottime.txt``, then:

  1. writes ``profiling/flamegraph_analysis_<date>.md`` from a template;
  2. stamps a superseded banner on the previous newest write-up;
  3. repoints ``profiling/webview/index.html`` (date, headline numbers, links);
  4. repoints the profiling bullet in ``profiling/scripts/README.md``.

Paths come from env (sane defaults):
  SCREENER_REPO - repo root (default: git toplevel of CWD)
  ANALYSIS_DIR  - scratch dir holding flamegraph_results.json (default ./profiling/_analysis)
  WEBVIEW_DIR   - webview dir holding pstats + html (default ./profiling/webview)
"""

from __future__ import annotations

import json
import os
import re
from datetime import date
from pathlib import Path

REPO = Path(os.environ.get("SCREENER_REPO", os.getcwd()))
SP = Path(os.environ.get("ANALYSIS_DIR", REPO / "profiling" / "_analysis"))
WEBVIEW = Path(os.environ.get("WEBVIEW_DIR", REPO / "profiling" / "webview"))
SCRIPTS = REPO / "profiling" / "scripts"

D = json.loads((SP / "flamegraph_results.json").read_text())


def own_code_rows() -> list[tuple[float, int, str]]:
    """Top own-code functions by cumulative time from pstats_cumulative.txt."""
    rows: list[tuple[float, int, str]] = []
    lines = (WEBVIEW / "pstats_cumulative.txt").read_text().splitlines()
    for ln in lines:
        m = re.match(r"\s*(\d+)\s+([\d.]+)\s+[\d.]+\s+([\d.]+)\s+[\d.]+\s+(\S+):(\d+)\((.*)\)", ln)
        if not m:
            continue
        ncalls, tt, cumtime, path, lineno, name = (
            int(m.group(1)), float(m.group(2)), float(m.group(3)),
            m.group(4), m.group(5), m.group(6),
        )
        if "/screener/" not in path or "/site-packages/" in path:
            continue
        rows.append((cumtime, ncalls, f"{path.split('/screener/')[-1]}:{lineno}({name})"))
    rows.sort(reverse=True)
    return rows[:12]


def pct_of_total(cumtime: float) -> float:
    return 100.0 * cumtime / D["instrumented_after"]["seconds"]


def render_table(rows: list[tuple[float, int, str]]) -> str:
    if not rows:
        return "_pstats not found - table omitted._\n"
    out = [
        "| Rank | Function | ncalls | cumtime | % |",
        "|---|---|---:|---:|---:|",
    ]
    for i, (cumtime, ncalls, name) in enumerate(rows, 1):
        out.append(
            f"| {i} | `{name}` | {ncalls:,} | {cumtime:.3f} s | {pct_of_total(cumtime):.1f}% |"
        )
    return "\n".join(out)


def mean(vals: list[float]) -> float:
    return sum(vals) / len(vals)


def fmt_trials(vals: list[float]) -> str:
    return " / ".join(f"{v:.3f}" for v in vals)


b_m, a_m = D["before_mean_s"], D["after_mean_s"]
speedup = b_m / a_m if a_m else float("nan")
b_call, b_sec = D["instrumented_before"]["calls"], D["instrumented_before"]["seconds"]
a_call, a_sec = D["instrumented_after"]["calls"], D["instrumented_after"]["seconds"]

doc = f"""# Flamegraph analysis re-run ({D["date"]})

**Engine:** rolling backtester · **Source of truth:** `profiling/webview/rolling.prof`
**Generated by:** `profiling/scripts/run_flamegraph.sh` — do not hand-edit the
numbers; re-run the script instead.

## 1. Method

Same offline harness, same seed, interleaved on one box:

```
profiling/harness.py {D["harness"]}
```

`{D["deps"]}`, BLAS threads pinned to 1. Two worktrees with the editable-install
`.pth` verified (`screener.__file__` inside each tree), so the only variable is
the code. Wall-clock trials interleaved before → after.

- **before** — `{D["before_commit"]}`, the pre-#114 merge-base (preserved as
  `profiling/webview/rolling_pre_vectorization.prof`).
- **after** — `{D["after_commit"]}`, the current tree.

**Box:** {D["box"]}. Absolute seconds are only comparable within this batch.

## 2. Wall clock ({D["trials"]} interleaved trials, {D["harness"].split('--repeat')[-1].strip()} per run)

| arm | trials (s/run) | mean |
|---|---|---:|
| before (`{D["before_commit"]}`) | {fmt_trials(D["before_trials_s"])} | **{b_m:.3f} s** |
| after (`{D["after_commit"]}`) | {fmt_trials(D["after_trials_s"])} | **{a_m:.3f} s** |

before → after: **{b_m:.3f} → {a_m:.3f} s/run, ≈{speedup:.2f}×**; both arms
produce **{D["trades"]} trades, {D["warnings"]} warnings**.

## 3. Instrumented totals (cProfile, engine only)

| arm | calls | seconds |
|---|---:|---:|
| before | {b_call:,} | {b_sec:.3f} |
| after | {a_call:,} | {a_sec:.3f} |

(−{100 - 100 * a_call / b_call:.0f}% calls, −{100 - 100 * a_sec / b_sec:.0f}%
instrumented time.)

## 4. Where the time goes now

Cumulative-time share of the {a_sec:.3f} s instrumented profile, own code only:

{render_table(own_code_rows())}

> Ranking is regenerated from `profiling/webview/pstats_cumulative.txt` by
> `gen_flamegraph_doc.py`, so it always reflects the current profile.

## 5. GPU verdict

Float math proper is a rounding error of the profile; the cost is pandas
dispatch, index hashing and object construction. Nothing here is GPU-shaped. At
~{a_m:.2f} s/run on this box the cheap win is the #1 own-code leaf above, not
hardware.
"""

out = REPO / "profiling" / f"flamegraph_analysis_{D['date'].replace('-', '_')}.md"
out.write_text(doc)
print(f"  wrote {out.relative_to(REPO)}")


def stamp_superseded() -> None:
    """Banner the previous newest write-up (all but the just-written one)."""
    docs = sorted(
        (REPO / "profiling").glob("flamegraph_analysis_20*.md")
    )
    mine = out.name
    prev = [p for p in docs if p.name != mine]
    if not prev:
        return
    newest = prev[-1]
    text = newest.read_text()
    if "Superseded" in text.splitlines()[0] + text.splitlines()[1]:
        return  # already stamped
    banner = (
        f"> **Superseded {D['date']}.** "
        f"[`{mine}`]({mine}) is the current re-run; its numbers supersede this "
        f"document. Regenerate via `profiling/scripts/run_flamegraph.sh`.\n\n"
    )
    # Insert after the H1 title line.
    lines = text.splitlines()
    insert_at = 1
    if lines[0].startswith("# "):
        while insert_at < len(lines) and lines[insert_at].strip():
            insert_at += 1
    lines.insert(insert_at, "")
    lines.insert(insert_at, banner.rstrip("\n"))
    newest.write_text("\n".join(lines) + "\n")
    print(f"  stamped superseded banner on {newest.name}")


stamp_superseded()


def update_index_html() -> None:
    idx = WEBVIEW / "index.html"
    html = idx.read_text()
    sub_new = (
        f'<div class="sub">Rolling engine · {D["harness"].split("--tickers")[1].split("--years")[0].strip()} '
        f'synthetic symbols · profile re-run {D["date"]} (deps pinned)</div>'
    )
    html = re.sub(r'<div class="sub">[^<]*</div>', sub_new, html, count=1)
    html = re.sub(
        r'profile re-run \d{4}-\d{2}-\d{2} \(post-rebase, deps pinned\)',
        f"profile re-run {D['date']} (deps pinned)",
        html,
        count=1,
    )
    html = re.sub(
        r'<h2>Profile re-run[^<]*</h2>',
        f"<h2>Profile re-run — {D['date']}</h2>",
        html,
        count=1,
    )
    # Repoint the "Re-run write-up" button and swap the previous one to alt.
    btn = re.search(
        r'<a class="btn(?: alt)?" href="(\.\./flamegraph_analysis_\d{4}_\d{2}_\d{2}\.md)">[^<]*</a>',
        html,
    )
    if btn:
        new_name = out.name
        html = html.replace(
            btn.group(0),
            f'<a class="btn" href="../{new_name}">Re-run write-up ({D["date"]}) →</a>',
            1,
        )
    idx.write_text(html)
    print(f"  updated {idx.relative_to(REPO)}")


update_index_html()


def update_scripts_readme() -> None:
    rd = SCRIPTS / "README.md"
    text = rd.read_text()
    pat = re.compile(r"- \*\*Profiling\.\*\*.*?(?=\n- |\n\n)", re.S)
    bullet = (
        f"- **Profiling.** Current ranking is in `../flamegraph_analysis_{D['date'].replace('-', '_')}.md` "
        f"(auto-generated {D['date']} by `run_flamegraph.sh`; interleaved before → after on one box: "
        f"**{b_m:.3f} s → {a_m:.3f} s per run, ≈{speedup:.2f}×**; {D['trades']} trades / {D['warnings']} "
        f"warnings on both arms). `panel_index_key` in `pine.py:721` is the #1 leaf at ~25%."
    )
    text, n = pat.subn(bullet, text, count=1)
    if n == 0:
        print("  WARN: could not find Profiling bullet in scripts/README.md")
    else:
        rd.write_text(text)
        print(f"  updated {rd.relative_to(REPO)}")


update_scripts_readme()
